### ISSUE TITLE
Save initial data passed to @wora/relay-store Store

### ISSUE THREAD

**Issue by kmjennison** [morrys/wora#16]
The `relay-runtime` Store will persist data you pass to it during initialization, such as `new Store(new RecordSource(records))`. It would be helpful if the `@wora/relay-store` Store had this behavior as well.

One use case:
https://github.com/morrys/react-relay-offline/issues/23

**Comment by morrys** [comment]
To facilitate data initialization and align the store with the original version, the first step is to change the creation of the store:

now:
```
const store = new Store();
const environment = new Environment({network, store});
```

after:
```
const recordSource = new RecordSource();
const store = new Store(recordSource);
const environment = new Environment({network, store});
```

**Comment by morrys** [comment]
this replaces the entire state previously persisted with the initial state, otherwise you can use other libraries to merge the two states
const recordSourceOptions = { mergeState: (restoredState) => initialState }


const recordSource = new RecordSource(recordSourceOptions);
const store = new Store(recordSource);
const environment = new Environment({network, store});

I have just released the new releases that should also solve this problem :)

Today I could not try your example project, I would like your feedback.

Thanks,
Lorenzo

**Comment by kmjennison** [comment]
@morrys I tried out v0.11.0 in this commit but couldn't get it working:
https://github.com/kmjennison/nextjs-demo/commit/ee7284093a629ee4e424d3b05003f1b3028c0f80

This commit replaces the workaround we discussed [here](https://github.com/morrys/react-relay-offline/issues/23#issuecomment-536120168).

It looks like `mergeState` is never called. Am I overlooking something?

**Comment by morrys** [comment]
Hi @kmjennison, 
since the store persisted in the storage it is always required to call their restore() function.
I took a look at the project and it looks like you didn't use any react-relay-offline component except for creating the environment.

react-react-offline [fetchQuery](https://github.com/morrys/react-relay-offline#fetchquery) automatically provides for the restore of the store, as well as its [QueryRenderer](https://github.com/morrys/react-relay-offline#queryrenderer). Otherwise, I also provided the hooks [useRestore](https://github.com/morrys/react-relay-offline#userestore)

**Comment by kmjennison** [comment]
Ok, thanks. I hope to put together a working demo of react-relay-offline with Next.js and a service worker, but I probably won't have time to work on it for a while.

**Comment by morrys** [comment]
Your proposal has been helpful in solving two SSR problems, in the weekend I release the fix on offline-first and I will put the project in offline-examples.
When you have time I would like you to try it and all the PR that will improve it will be appreciated :)

**Comment by morrys** [comment]
I believe this is closed with the release of the latest versions and the test carried out here:
https://github.com/morrys/react-relay-offline/issues/23#issuecomment-541447437

If there should be other problems, open another issue as well :)

**Comment by morrys** [comment]
From the tests carried out in the [example project of offline relay with nextjs](https://github.com/morrys/offline-examples/tree/master/relay/nextjs), a change to the data initialization management is necessary in order to make the SSR easier.

`mergeState: (restoredState, initialState) => mergeState`

**Comment by morrys** [comment]
Released the new version of cache-persist that allows a better management of initial data.
https://github.com/morrys/wora/releases/tag/cache-persist%402.0.3
